### ISSUE TITLE
Nggak fungsi Pak

### ISSUE THREAD

**Issue by purbojati** [benedictjohannes/bca-pdfestatement-extractor#1]

**Comment by benedictjohannes** [comment]
Terima kasih untuk issue nya. 
Yang tidak berfungsi  bagaimana Pak? 
Apakah bapak coba yang di web? Atau yang executable nya?

**Comment by superipey** [comment]
![image](https://github.com/user-attachments/assets/01f23b23-c93f-4104-83b2-ae4345a96f60)

Pas upload muncul error ini pak.

**Comment by superipey** [comment]
<img width="869" alt="image" src="https://github.com/user-attachments/assets/44de01a5-1671-410d-b523-4fe35c3a2d1b">

lewat console jg sama pak

**Comment by purbojati** [comment]
Saya akhirnya bikin tools sendiri pak. Boleh cek di rekeningkoran.com

**Comment by benedictjohannes** [comment]
> <img alt="image" width="869" src="https://private-user-images.githubusercontent.com/16450242/380696432-44de01a5-1671-410d-b523-4fe35c3a2d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzE5ODMsIm5iZiI6MTczMDIzMTY4MywicGF0aCI6Ii8xNjQ1MDI0Mi8zODA2OTY0MzItNDRkZTAxYTUtMTY3MS00MTBkLWI1MjMtNGZlMzVjM2EyZDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE5NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjAyZDVmZmViYmZmMWI0YjM5MDg3MzIxYzFiMTY3MTkwNTEwZWU0MDc4NDFjMDI2NWU2ZmYwMDllZmYxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mWbIPtalkcz8onmnBi7YRLduaouOiSCbvdwo1d6-w-s">
> lewat console jg sama pak

@superipey terima kasih untuk memberikan error detail. Saya jadinya sengaja coba download eStatement PDF dari BCA rekening pribadi saya dan memang benar, ternyata error persis seperti yang bapak dapatkan.  
Sepertinya BCA melakukan perubahan pada PDF nya yang membuat PDF nya jadi tidak kebaca oleh [library](https://github.com/ledongthuc/pdf) yang saya gunakan untuk baca PDF.

Bertanya, krn sy sudah lama tidak pakai app ini, apakah masih ada yang berminat pakai? Kalau ada, sy akan usahakan untuk update aplikasinya.

@purbojati thanks sudah buka issue awal ini. Sy dulu membuat tool simple ini krn pengen rapi-rapi rekening pribadi + PT yang sy handle. Approach sy membuat versi web nya adalah go layer nya sy jadikan wasm, dan sama sekali tidak ada upload ke server krn sy memang tidak punya monetazion strategy untuk aplikasi ini. Selamat sudah berhasil membuat aplikasinya Pak. Sepertinya server side ya Pak jadi processing di dalam server? Jd pensaran bapak buat fairly complete feature nya, apakah memang pengen dijadikan produk (yang dijual)?

**Comment by purbojati** [comment]
@benedictjohannes betul, Pak. Jika nanti bank sudah komplit, kemungkinan akan mulai di monetisasi. Namun tidak dalam waktu dekat karena ini weekend project saja bagi saya.

**Comment by superipey** [comment]
@benedictjohannes ya saya pakai tools sebelah yang mirip https://tinybanktools.netlify.app/bcaExport tapi kedepannya jika bapak mau mengembangkan code ini, mau saya coba integrasikan dengan web yg saya miliki

**Comment by keyennn** [comment]
> > <img alt="image" width="869" src="https://private-user-images.githubusercontent.com/16450242/380696432-44de01a5-1671-410d-b523-4fe35c3a2d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzE5ODMsIm5iZiI6MTczMDIzMTY4MywicGF0aCI6Ii8xNjQ1MDI0Mi8zODA2OTY0MzItNDRkZTAxYTUtMTY3MS00MTBkLWI1MjMtNGZlMzVjM2EyZDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE5NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjAyZDVmZmViYmZmMWI0YjM5MDg3MzIxYzFiMTY3MTkwNTEwZWU0MDc4NDFjMDI2NWU2ZmYwMDllZmYxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mWbIPtalkcz8onmnBi7YRLduaouOiSCbvdwo1d6-w-s">
> > lewat console jg sama pak
> 
> @superipey terima kasih untuk memberikan error detail. Saya jadinya sengaja coba download eStatement PDF dari BCA rekening pribadi saya dan memang benar, ternyata error persis seperti yang bapak dapatkan. Sepertinya BCA melakukan perubahan pada PDF nya yang membuat PDF nya jadi tidak kebaca oleh [library](https://github.com/ledongthuc/pdf) yang saya gunakan untuk baca PDF.
> 
> Bertanya, krn sy sudah lama tidak pakai app ini, apakah masih ada yang berminat pakai? Kalau ada, sy akan usahakan untuk update aplikasinya.
> 
> @purbojati thanks sudah buka issue awal ini. Sy dulu membuat tool simple ini krn pengen rapi-rapi rekening pribadi + PT yang sy handle. Approach sy membuat versi web nya adalah go layer nya sy jadikan wasm, dan sama sekali tidak ada upload ke server krn sy memang tidak punya monetazion strategy untuk aplikasi ini. Selamat sudah berhasil membuat aplikasinya Pak. Sepertinya server side ya Pak jadi processing di dalam server? Jd pensaran bapak buat fairly complete feature nya, apakah memang pengen dijadikan produk (yang dijual)?

Halo Pak @benedictjohannes boleh pak diupdate aplikasinya, saya sering pakai aplikasi bapak.

**Comment by tonoman3g** [comment]
> library



> > <img alt="image" width="869" src="https://private-user-images.githubusercontent.com/16450242/380696432-44de01a5-1671-410d-b523-4fe35c3a2d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzE5ODMsIm5iZiI6MTczMDIzMTY4MywicGF0aCI6Ii8xNjQ1MDI0Mi8zODA2OTY0MzItNDRkZTAxYTUtMTY3MS00MTBkLWI1MjMtNGZlMzVjM2EyZDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE5NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjAyZDVmZmViYmZmMWI0YjM5MDg3MzIxYzFiMTY3MTkwNTEwZWU0MDc4NDFjMDI2NWU2ZmYwMDllZmYxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mWbIPtalkcz8onmnBi7YRLduaouOiSCbvdwo1d6-w-s">
> > lewat console jg sama pak
> 
> @superipey terima kasih untuk memberikan error detail. Saya jadinya sengaja coba download eStatement PDF dari BCA rekening pribadi saya dan memang benar, ternyata error persis seperti yang bapak dapatkan. Sepertinya BCA melakukan perubahan pada PDF nya yang membuat PDF nya jadi tidak kebaca oleh [library](https://github.com/ledongthuc/pdf) yang saya gunakan untuk baca PDF.
> 
> Bertanya, krn sy sudah lama tidak pakai app ini, apakah masih ada yang berminat pakai? Kalau ada, sy akan usahakan untuk update aplikasinya.
> 
> @purbojati thanks sudah buka issue awal ini. Sy dulu membuat tool simple ini krn pengen rapi-rapi rekening pribadi + PT yang sy handle. Approach sy membuat versi web nya adalah go layer nya sy jadikan wasm, dan sama sekali tidak ada upload ke server krn sy memang tidak punya monetazion strategy untuk aplikasi ini. Selamat sudah berhasil membuat aplikasinya Pak. Sepertinya server side ya Pak jadi processing di dalam server? Jd pensaran bapak buat fairly complete feature nya, apakah memang pengen dijadikan produk (yang dijual)?

saya minat pakai, sangat membantu sekali, cuma sayang, untuk mutasi rekening mulai agustus 2024, mulai dapat error 

err: malformed PDF: 256-bit encryption key
